package com.cognitest.testcases;

import com.listener.TestListener;
import com.page.base.MenuPage;
import com.page.base.CognitestPageHook;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;
import org.testng.annotations.DataProvider;
import java.io.FileReader;
import com.google.gson.JsonParser;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

@Listeners(TestListener.class)
public class TC_258_003 extends CognitestPageHook {

    @BeforeTest
    public void setReportValues() {
        testcaseName = "TC-258-003 User logs in and performs a search with only the Transaction ID field populated.";
        testDescription = "User logs in and performs a search with only the Transaction ID field populated.";
        authors = "Cognitest";
        category = "MCP Automation";
    }

    @DataProvider(name = "testData")
    public Object[][] getTestData() {
        String testDataPath = "src/test/java/com/cognitest/testcases/TestData/testData_TC-258-003.json"; // Hardcoded path to the data file
        List<Object[]> data = new ArrayList<>();
        try (FileReader reader = new FileReader(testDataPath)) {
            JsonObject jsonObject = JsonParser.parseReader(reader).getAsJsonObject();
            JsonArray tcDataArray = jsonObject.getAsJsonArray("TestData");
            
            // Create ONE map for the entire test run BEFORE the loop
            Map<String, String> currentRunData = new HashMap<>();

            // Loop through all field-value pairs and populate the SINGLE map
            for (int i = 0; i < tcDataArray.size(); i++) {
                JsonObject item = tcDataArray.get(i).getAsJsonObject();
                String fieldName = item.get("fieldName").getAsString();
                String value = item.get("value").getAsString();
                currentRunData.put(fieldName, value);
            }
            // Add the completed map to data AFTER the loop completes for the @Test method
            data.add(new Object[]{currentRunData}); 
        } catch (Exception e) {
            e.printStackTrace();
            // Handle error appropriately, e.g., throw a runtime exception or log
        }
        return data.toArray(new Object[0][0]);
    }

    @Test(dataProvider = "testData")
    public void autogeneratedtest(Map<String, String> testData) throws InterruptedException {
        new MenuPage()
            .navigateToHomePage()
            .verifyTickingMindsText()
            .fillEmail(testData.get("EMAIL"))
            .verifyEmail(testData.get("EMAIL"))
            .fillPassword(testData.get("PASSWORD"))
            .verifyPassword(testData.get("PASSWORD"))
            .clickLoginButton()
            .verifyInsuranceSearchText()
            .fillTransactionId(testData.get("TRANSACTION_ID"))
            .verifyTransactionId(testData.get("TRANSACTION_ID"))
            .clickSearchButton()
            .verifySearchResultsText()
            .clickTransactionLink(testData.get("TRANSACTION_ID"))
            .verifyTransactionInformationText();
        
        System.out.println("ATS created successfully for " + testcaseName);
    }
}